### PR TITLE
Added Newfpga page

### PR DESCRIPTION
**Pull request by ChucklesOnGitHub**
Added new page with instructions on how to work with the new OE FPGA.
I couldn't get this page to show up in the left menu for all the pages of the User Manual, only User Manual and Gateware.

### CODE REVIEW

**Comment by jsiegle** [comment]
If you run `make clean` and then `make` again it will show up

**Comment by ChucklesOnGitHub** [comment]
yup works now, thks

**Review by jsiegle — APPROVED** [review]
Just pushed a few small changed! I think it's ready to merge.

**Comment by jsiegle** [comment]
I think this is good to go...we will add the Linux/Mac instructions once those versions of the plugin have been released

**Pull request merged**
